jerakia/jerakia

- lib/jerakia.rb
- lib/jerakia/config.rb
Instead of taking a configuration file as a parameter to the `#initialize`
method on `Jerakia::Config`, let's take a hash of configuration options.
This lets us configure Jerakia in different ways (from a configuration
file being just one of them). This means that I can change Jerakia's
configuration at runtime (I'm specifically thinking during testing). I'm
also adding the `load_from_file` method so we can still load from a
configuration file. This commit also cleans up a few things in the
Jerakia class.
> Allowing Jerakia::Config to take a hash

- lib/jerakia/datasource.rb
Scenario: when an option is specified as "Integer" the actual `.class` method in ruby returns `Fixnum` - the old method of handling data types meant these two were not equal, but they should be...
```ruby
[6] pry(#<Jerakia::Datasource>)> 1.is_a?(Integer)
=> true
[7] pry(#<Jerakia::Datasource>)> 1.is_a?(Fixnum)
=> true
```
```ruby
[3] pry(#<Jerakia::Datasource>)> @options[opt].class
=> Fixnum
```
Using is_a? in a select makes this compatible
> Bugfix: better handling of options validation for datasource.

- lib/jerakia/lookup/plugin/hiera.rb
For example, if searching for the key "classes" it would search for "::classes"; Which, in this instance, would break a hiera_include.
> Hiera plugin should not prepend "::" to keys when there is no namespace

- lib/jerakia/lookup/plugin/hiera.rb
Autorun will always delete the namespace and and merge the "calling_module" into the key - so we need to get the calling_module from the key, not the namespace.
> dont derive calling_module from namespace

- lib/jerakia.rb
- lib/jerakia/dsl/lookup.rb
- lib/jerakia/dsl/policy.rb
- lib/jerakia/launcher.rb
- lib/jerakia/lookup.rb
- lib/jerakia/policy.rb
- lib/jerakia/schema.rb
- test/fixtures/etc/jerakia/policy.d/default.rb
This commit refactors a lot of stuff surrounding how we parse the
DSL.  It adds some separation between the core lookup and policy
libraries and the DSL.  It's part of a larger overhaul of how we
parse DSL
> Refactor of DSL parser

- .travis.yml
- Rakefile
- lib/jerakia/policy.rb
Marshal.dump was causing some strange errors under very specific
circumstances when jerakia was run through puppet.  This commit
replaces this with "request.clone" which passes the failing
tests
@hhenkel FYI
> Changed marshal dump for clone

- lib/jerakia/policy.rb
- test/fixtures/etc/jerakia/policy.d/default.rb
- test/fixtures/var/lib/jerakia/schema/test.json
This bug can be simulated by having two lookups, where the first
lookup is valid but returns no data, so the second lookup is used.
In this scenario, an exception is raised because the first lookup
sets the answers payload to {} and the second lookup tries to
append to it.
`test/fixtures/etc/jerakia/policy.d/default.rb` has a policy file
that simulates it, if you look up a cascading hash using this policy
it will fail with an exception.
This commit changes the code flow and gathers all the responses from
all the lookups first, before parsing the answer object.  The policy code to trigger this is:
```ruby
policy :default do
lookup :invalid do
datasource :file, {
:docroot    => "test/fixtures/var/lib/jerakia/data",
:format     => :yaml,
:searchpath => [
"invalid",
],
}
end
lookup :default …
```
> Bug: multiple lookups with hashes sometimes caused exception

- lib/jerakia/datasource.rb
If a data source has a boolean option defaulting to true,  setting false in the policy will not override the value... this fixes the issue by evaluating on `nil?` rather than true when deciding whether or not to use defaults.
> Fixed: data source boolean options 

- lib/jerakia/datasource/http.rb
As raised in https://github.com/crayfishx/lookup_http/issues/2 Jerakia will fail if it doesn't get a hash from the lookup_http call.  This fixes the issue and will not throw an exception if failure is set to `:graceful`
> Allow http datasource to return nil when failure is set to :graceful

- lib/hiera/backend/jerakia_backend.rb
- lib/jerakia/cli.rb
- lib/jerakia/policy.rb
- lib/puppet/indirector/data_binding/jerakia.rb
- test/fixtures/etc/jerakia/policy.d/hiera.rb
The hiera metadata added Puppet::Resource objects for metaparameters like before, require...etc, these caused Marshal.dump to fail when cloning the request.  Removing Marshal.dump caused other issues (see #60 ) - this PR addresses the initial problem by filtering out `Puppet::Resource` objects from the metadata and reverting the clone back to `Marshal.dump/Marshal.load`
Also - thor now freezes options by default, this was causing problems cloning when using the command line
* Reject `Puppet::Resource` from metadata (hiera backend)
* Duplicate the options hash so options aren't frozen (CLI)
* Reverted the clone method back to Marshal.dump
> Bugfixes for cloning.

- lib/jerakia/lookup.rb
- lib/jerakia/lookup/plugin.rb
- lib/jerakia/lookup/plugin_config.rb
- test/fixtures/etc/jerakia/jerakia.yaml
This adds the capability to plugins to be configured directly from
jerakia.yaml.  Config can be placed in the 'plugins' hash under a key
representing the plugin name, Jerakia::Lookup::PluginConfig is a class
who's instances expose the underlying hash to the lookup plugin from
the config method.
Eg: the following configuration in jerakia.yaml
```yaml
plugins:
myplugin:
setting: value
```
is referenced in the lookup plugin myplugin as
```
config[:setting]  # => "value"
```
Currently the hash is also passed as a hash to the autorun method of
the pllugin - this will be deprecated in a future version.
> Add config method to lookup plugins.

- lib/jerakia/scope/puppetdb.rb
- test/fixtures/var/lib/jerakia/data/host/agent1/test.yaml
This PR adds a PuppetDB scope handler to Jerakia.... eg
`jerakia lookup port -n apache --scope puppetdb --scope-options node:agent1.localdomain`
> PuppetDB Scope handler.

- .gitignore
- lib/jerakia/scope/server.rb
- lib/jerakia/server/auth/token.rb
- lib/jerakia/server/rest.rb
- lib/jerakia/server/token.rb
- test/fixtures/etc/jerakia/jerakia.yaml
This PR adds a new scope handler called 'server'.... This allows Jerakia itself to store a local copy of the scope (facts, for Puppet integration).  This stems from a conversation on slack with Henrik regarding the new lookup functionality expected in Puppet 4.9, and will also enable us to deprecate the current ruby bindings for the hiera backend and data_binding_terminus in favour of REST API calls to Jerakia Server, thus de-coupling Puppet and Jerakia from being tied together at the ruby level.  Since using the puppetDB scope handler is impractical for Puppet runs because there is no guarantee that the facts in puppetDB will be the latest at the point that data lookups are done.  We don't want to have to send all the facts to Jerakia everytime we want to do a data lookup as that means …
> added server scope, api endpoints and various bug fixes for 1.2

- lib/jerakia/config.rb
- lib/jerakia/server.rb
- lib/jerakia/server/rest.rb
The biggest bottleneck for API calls to Jerakia Server seems to be calls to the database to verify the token - by adding `token_ttl` (default 300 seconds) then the token is cached in memory and only refreshed once the cache expires.  This makes a massive difference to the response time of the API
> Add token_ttl option to server.

- lib/jerakia/server/rest.rb
- test/fixtures/var/lib/jerakia/data/common/test.yaml
This PR tries to solve the inconsistency mentioned in #95 and adds support for [msgpack](http://msgpack.org/) as an alternative to JSON for the jerakia api server. It does not try to alter the behavior of interpreting numerical keys with leading zeros as octal numbers.
For backwards compatibility I tried to keep the current behavior of using JSON as a default when no content type header is set. I also added the possibility to set the content type to `application/json` and made it the default in my jerakia-client implementation.
When a client sends a request with `application/x-msgpack` the server replies with the msgpack format. 
As other content types are currently not supported the server should inform the client about that - this is done via [HTTP Error …
> Add msgpack support to jerakia

- bin/jerakia
- lib/jerakia/cli.rb
- lib/jerakia/log.rb
- lib/jerakia/server/auth/token.rb
Particularly when installing from a Gem, Jerakia fails to start until a few bits of scaffolding are in place, mainly the `databasedir` and `logfile`.  In the case of logging Jerakia would throw an exception and bail out - this is frustrating and a bit unneccesary this PR changes the behaviour so logs are redirected to `STDOUT` and gives the following warning if the logfile cannot be opened;
`I, [2017-08-11T14:29:47.695526 #17466]  INFO -- : Failed to open logfile: Permission denied @ rb_sysopen - /var/log/jerakia/jerakia.log, logs will be directed to STDOUT`
But Jerakia will not throw an exception and will keep on running with logs going to `STDOUT`
In the case of the `databasedir` being unavailable or unwritable, this caused Jerakia to throw an exception that was confusing to understand …
> improved error reporting and softer handline of no log file

- lib/jerakia/answer.rb
- lib/jerakia/datasource/file.rb
- lib/jerakia/datasource/http.rb
- lib/jerakia/policy.rb
- lib/jerakia/server/rest.rb
- test/fixtures/var/lib/jerakia/data/common/test.yaml
Closes #102 
Currently there is no way to differentiate between a key explicitly set as NULL
Eg:
```yaml
foo: ~
```
Should return nul but we should know that this was explicitly set to null and not unresolved.
This will be used to determine the HTTP response code with a 404 being returned for not found and a 200 returned for found in the v2 API, for now, in v1 we just add this as a `found` field to the return data to keep backwards compatibility.
Backends should only call `response.submit` if they have found a value - failure to invoke the method will mean `found` is set to `false`.  The HTTP and File backends have been updated to reflect this.
> Added found attribute to answers to differentiate null from not found

- lib/jerakia/datasource.rb
- lib/jerakia/datasource/file.rb
- test/fixtures/etc/jerakia/policy.d/default.rb
Due to a bug in the option handling of the new datasource API in
2.0.0 defaults for datasource options were not being set.  This
can be tested by the removal of `:format => :yaml` in the test
policy as this should be set by the file datasource as a default.
This affects datasources that declare options like;
`option :foo, :default => :bar`
Also this commit fixes a typo with the `extension` option of the
file resource that was mistyped `extention` and therefore meant
this option would not work.
> Bugfix: Datasource option defaults not being set.

- lib/jerakia/answer.rb
- lib/jerakia/response.rb
- lib/jerakia/response/entry.rb
- lib/jerakia/response/filter.rb
- lib/jerakia/response/filter/dig.rb
- lib/jerakia/util.rb
- spec/features/filter_dig_spec.rb
- spec/features/filter_strsub_spec.rb
- test/fixtures/etc/jerakia/lib/jerakia/encryption/dummy.rb
- test/fixtures/etc/jerakia/policy.d/default.rb
- test/fixtures/etc/jerakia/policy.d/dig.rb
- test/fixtures/var/lib/jerakia/data/common/test.yaml
Closes #111 
This adds an output handler called dig that lets you drill into
returned hash results and pull out a key
Eg: if a datasource returns;
```
{
"document" => {
"settings" => {
"foo" => "bar"
}
}
}
```
if we are only interested in the key foo (assuming the lookup key
is foo) then we can dig this in the lookup with
`output_filter :dig, [ 'document', 'settings', request.key ]`
> Added dig output handler

- lib/jerakia/datasource/http.rb
This resolves the final points from issue #111 
This enabled the http datasource *not* to dig for any data and return the whole hash by setting `:lookup_key => false`
This will likely default to being false Jerakia 3.0.0 but for backward compatibility this is currently opt in
> added lookup_key switch to httpd datasource.

- lib/jerakia/datasource/file.rb
Seem like the logic for toggling the cache on and off was broken. This is a
potential fix and renames the var for clarity.
> FIX: Logic for toggling cache was broken

- lib/jerakia/datasource/http.rb
- lib/jerakia/version.rb
As per the documentation and comments, lookup_key is changing
to a default value of false in Jerakia 3.0 - this is mainly
due to the limited flexibility offered by the HTTP datasource
in digging into data structures using lookup_key - which expects
the top level keys of the returned hash from the HTTP end point
to be the same as the request keys... This is rarely enough
The better way of doing this is to set `lookup_key` to `false`
and use the `dig` filter in the lookup which is far more
flexible.
> [BREAK] HTTP Datasource: default lookup_key false

- jerakia.docker
When gracefully stopping a container, Docker will send the SIGTERM
signal to PID 1 inside container. Before this commit, this was bash
and not jerakia. bash doesn't do anything when receiving SIGTERM or
SIGINT. This made the container take a long time to stop correctly.
> Ensure Docker can target Jerakia directly to stop container
